backend:
  name: "git-gateway"
  branch: "master"
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "rssPosts"
    label: "RSS Posts"
    label_singular: "RSS Post"
    folder: "src/data/rss"
    create: true
    slug: "{{feedKey}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "rss-post" }
      - { label: "ID", name: "id", widget: "hidden" }
      - { label: "Organization", name: "feedKey", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Curated", name: "curated", widget: "boolean", required: false}
      - { label: "Image", name: "image", widget: "image", required: false }

  - name: "rssConfigs"
    label: "RSS Configs"
    label_singular: "RSS Config"
    folder: "src/data/rss/rssConfigs"
    create: true
    slug: "{{feedKey}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "rss-config" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Feed Key", name: "feedKey", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      

  - name: "fbEvents"
    label: "Events"
    label_singular: "Event"
    folder: "src/data/fb"
    create: true
    slug: "{{page}}-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "fb-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Organization", name: "page", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }

  - name: "fbConfigs"
    label: "Event Configs"
    label_singular: "Event Config"
    folder: "src/data/fb/fbConfigs"
    create: true
    slug: "{{pageKey}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "fb-config" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Key", name: "pageKey", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }

  - name: "irdResources"
    label: "Resources"
    label_singular: "Resource"
    folder: "src/data/ird"
    create: true
    slug: "ird-{{date}}-{{id}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "ird-resource" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: "Berkeley Affiliated", name: "calAffiliated", widget: "boolean", required: false}

  
  - name: "opportunities"
    label: "Opportunities"
    label_singular: "Opportunity"
    folder: "src/data/opportunities"
    create: true
    slug: "{{slug}}-{{date}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "opportunity" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Url", name: "url", widget: "string" }
      - { label: "Organization", name: "org", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false}
      - { label: "Date", name: "date", widget: "datetime" }
      
  - name: "courses"
    label: "Courses"
    label_singular: "Course"
    folder: "src/data/courses"
    create: true
    slug: "{{courseKey}}-{{id}}"
    extension: json
    identifier_field: number
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "course" }
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Course Key", name: "courseKey", widget: "string" }
      - { label: "Number", name: "number", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Units", name: "units", widget: "number" }
      - { label: "Department", name: "department", widget: "string" }

  - name: "courseConfigs"
    label: "Course Configs"
    label_singular: "Course Config"
    folder: "src/data/courses/coursesConfigs"
    create: true
    slug: "{{courseKey}}"
    extension: json
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "course-config" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Course Key", name: "courseKey", widget: "string" }
      - { label: "ID", name: "id", widget: "string" }